In [1]:
import StatsBase: countmap 

In [7]:
dict = countmap([1,1,2,4,1,5,12,1,51,2,5])  

Dict{Int64,Int64} with 6 entries:
  4  => 1
  2  => 2
  5  => 2
  51 => 1
  12 => 1
  1  => 4

In [3]:
?countmap

search: countmap



```
countmap(x; alg = :auto)
```

Return a dictionary mapping each unique value in `x` to its number of occurrences.

  * `:auto` (default): if `StatsBase.radixsort_safe(eltype(x)) == true` then use                    `:radixsort`, otherwise use `:dict`.
  * `:radixsort`:      if `radixsort_safe(eltype(x)) == true` then use the                    [radix sort](https://en.wikipedia.org/wiki/Radix_sort)                    algorithm to sort the input vector which will generally lead to                    shorter running time. However the radix sort algorithm creates a                    copy of the input vector and hence uses more RAM. Choose `:dict`                    if the amount of available RAM is a limitation.
  * `:dict`:           use `Dict`-based method which is generally slower but uses less                    RAM and is safe for any data type.


In [16]:
sortedDict = sort(collect(dict), by=x->x[2], rev=true)

6-element Array{Pair{Int64,Int64},1}:
  1 => 4
  2 => 2
  5 => 2
  4 => 1
 51 => 1
 12 => 1

In [22]:
winner = sortedDict[1][1]

1

In [9]:

?sort

search: sort sort! sortperm sortperm! sortslices Cshort issorted QuickSort



```
sort(v; alg::Algorithm=defalg(v), lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Variant of [`sort!`](@ref) that returns a sorted copy of `v` leaving `v` itself unmodified.

# Examples

```jldoctest
julia> v = [3, 1, 2];

julia> sort(v)
3-element Array{Int64,1}:
 1
 2
 3

julia> v
3-element Array{Int64,1}:
 3
 1
 2
```

---

```
sort(A; dims::Integer, alg::Algorithm=DEFAULT_UNSTABLE, lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Sort a multidimensional array `A` along the given dimension. See [`sort!`](@ref) for a description of possible keyword arguments.

To sort slices of an array, refer to [`sortslices`](@ref).

# Examples

```jldoctest
julia> A = [4 3; 1 2]
2×2 Array{Int64,2}:
 4  3
 1  2

julia> sort(A, dims = 1)
2×2 Array{Int64,2}:
 1  2
 4  3

julia> sort(A, dims = 2)
2×2 Array{Int64,2}:
 3  4
 1  2
```


In [23]:
struct LabeledPoint
    point
    label
    LabeledPoint(point, label) = new(point, label)
end 


In [42]:
point = [1.1,2.2]
label = "a";

lb = LabeledPoint(point, label)
lb2 = LabeledPoint([3.1,4], "b")
lb3 = LabeledPoint([1,2], "c")

LabeledPoint([1, 2], "c")

In [32]:
using Distances
r = SqEuclidean()([3,2], [1,2])

4

In [43]:
coll = [lb2, lb3, lb]
coll

3-element Array{LabeledPoint,1}:
 LabeledPoint([3.1, 4.0], "b")
 LabeledPoint([1, 2], "c")
 LabeledPoint([1.1, 2.2], "a")

In [44]:


sort!(coll, by = x -> SqEuclidean()(x.point, [1,2]))

3-element Array{LabeledPoint,1}:
 LabeledPoint([1, 2], "c")
 LabeledPoint([1.1, 2.2], "a")
 LabeledPoint([3.1, 4.0], "b")

In [48]:
using HTTP
r = HTTP.request("GET", "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Mon, 13 Jul 2020 22:59:50 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips SVN/1.7.14 Phusion_Passenger/4.0.53 mod_perl/2.0.11 Perl/v5.16.3
Last-Modified: Tue, 09 Mar 1993 00:27:15 GMT
ETag: "11c7-2996b79a79ec0"
Accept-Ranges: bytes
Content-Length: 4551
Content-Type: application/x-httpd-php

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5.0,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
5.4,3.7,1.5,0.2,Iris-setosa
4.8,3.4,1.6,0.2,Iris-setosa
4.8,3.0,1.4,0.1,Iris-setosa
4.3,3.0,1.1,0.1,Iris-setosa
5.8,4.0,1.2,0.2,Iris-setosa
5.7,4.4,1.5,0.4,Iris-setosa
5.4,3.9,1.3,0.4,Iris-setosa
5.1,3.5,1.4,0.3,Iris-setosa
5.7,3.8,1.7,0.3,Iris-setosa
5.1,3.8,1.5,0.3,Iris-setosa
5.4,3.4,1.7,0.2,Iris-setosa
5.1,3.7,1.5,0.4,Iris-setosa
4.6,3.6,1.0,0.2,Iris-setosa
5.1,3.3,

In [65]:
arr = []
push!(arr, "ab")

1-element Array{Any,1}:
 "ab"

In [81]:
data = open(f->read(f,String), "iris.data")
irislines = []
for i in split(data, "\n")
    push!(irislines,i)
end

split(irisline[1],",")
line = irisline[1]

row = split(line, ",")
row[1:end-1]
#measurements = [value for value in row[:length(row)-1]]

4-element Array{SubString{String},1}:
 "5.1"
 "3.5"
 "1.4"
 "0.2"

In [71]:
float("5.1")

MethodError: MethodError: no method matching AbstractFloat(::String)
Closest candidates are:
  AbstractFloat(!Matched::Bool) at float.jl:258
  AbstractFloat(!Matched::Int8) at float.jl:259
  AbstractFloat(!Matched::Int16) at float.jl:260
  ...

In [84]:
cm = Dict()
cm[("a","b")] = 1

1

In [86]:
cm["b","a"] = 2

2

In [87]:
cm

Dict{Any,Any} with 2 entries:
  ("b", "a") => 2
  ("a", "b") => 1

In [90]:
get(cm,("c","a"), 0)

0